# Generated by Django 5.2.17 on 2026-09-17 03:05

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('mask', models.CharField(blank=True, max_length=4)),
                ('account_type', models.CharField(choices=[('checking', 'Checking'), ('savings', 'Savings'), ('credit_card', 'Credit card')], max_length=20)),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('available_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('plaid_item_id', models.CharField(max_length=255, unique=True)),
                ('plaid_access_token_encrypted', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['institution_name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BudgetPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(unique=True)),
                ('end_date', models.DateField()),
                ('reset_day', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_envelope', models.BooleanField(default=True)),
                ('rollover_enabled', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('merchant_match_type', models.CharField(choices=[('contains', 'Contains'), ('exact', 'Exact')], default='contains', max_length=10)),
                ('merchant_pattern', models.CharField(max_length=255)),
                ('minimum_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('maximum_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('behavior', models.CharField(choices=[('suggest_only', 'Suggest only'), ('auto_apply', 'Auto-apply')], default='suggest_only', max_length=20)),
                ('confirmation_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='finance.account')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='finance.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Envelope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('rollover_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('budget_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envelopes', to='finance.budgetperiod')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envelopes', to='finance.category')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('budget_period', 'category'), name='unique_envelope_per_period_category')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaid_transaction_id', models.CharField(max_length=255, unique=True)),
                ('date', models.DateField()),
                ('merchant_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('posted', 'Posted')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('excluded_from_budget', models.BooleanField(default=False)),
                ('needs_review', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.account')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.category')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_transactions', to='finance.rule')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['date', 'status'], name='finance_tra_date_ad2c84_idx'), models.Index(fields=['needs_review', 'category'], name='finance_tra_needs_r_088bcd_idx')],
            },
        ),
    ]
