# Generated by Django 5.2.17 on 2026-09-17 23:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source', models.CharField(default='manual', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_paycheck_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('surplus_responsibilities_percent', models.PositiveSmallIntegerField(default=50)),
                ('surplus_savings_percent', models.PositiveSmallIntegerField(default=30)),
                ('surplus_discretionary_percent', models.PositiveSmallIntegerField(default=20)),
                ('savings_floor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paycheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_date', models.DateField()),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('received_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('expected', 'Expected'), ('received', 'Received')], default='expected', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['pay_date'],
            },
        ),
        migrations.CreateModel(
            name='PaycheckAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_reserve', models.BooleanField(default=False, help_text='Reserve money for a due-soon bill or essential obligation.')),
            ],
        ),
        migrations.CreateModel(
            name='RecurringBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('due_day', models.PositiveSmallIntegerField()),
                ('is_essential', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['due_day', 'name'],
            },
        ),
        migrations.AddField(
            model_name='budgetperiod',
            name='expected_income',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='transaction',
            name='kind',
            field=models.CharField(choices=[('expense', 'Expense'), ('income', 'Income'), ('transfer', 'Transfer'), ('adjustment', 'Adjustment')], default='expense', max_length=12),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transfer_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_transfers', to='finance.account'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['kind', 'status', 'date'], name='finance_tra_kind_f7088c_idx'),
        ),
        migrations.AddField(
            model_name='budgetallocation',
            name='budget_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_events', to='finance.budgetperiod'),
        ),
        migrations.AddField(
            model_name='budgetallocation',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_allocations', to='finance.category'),
        ),
        migrations.AddField(
            model_name='paycheckallocation',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paycheck_allocations', to='finance.category'),
        ),
        migrations.AddField(
            model_name='paycheckallocation',
            name='paycheck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='finance.paycheck'),
        ),
        migrations.AddField(
            model_name='recurringbill',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_bills', to='finance.account'),
        ),
        migrations.AddField(
            model_name='recurringbill',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_bills', to='finance.category'),
        ),
        migrations.AddConstraint(
            model_name='paycheckallocation',
            constraint=models.UniqueConstraint(fields=('paycheck', 'category'), name='unique_paycheck_category_allocation'),
        ),
        migrations.AddConstraint(
            model_name='recurringbill',
            constraint=models.CheckConstraint(condition=models.Q(('due_day__gte', 1), ('due_day__lte', 31)), name='recurring_bill_due_day_valid'),
        ),
    ]
