# Generated by Django 5.2.17 on 2026-09-17 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_budgetallocation_budgetsettings_paycheck_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetperiod',
            name='expected_income',
        ),
    ]
