# Generated by Django 5.2.17 on 2026-09-19 17:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_user_ownership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetperiod',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AddConstraint(
            model_name='budgetperiod',
            constraint=models.UniqueConstraint(fields=('owner', 'start_date'), name='unique_budget_period_per_owner'),
        ),
    ]
